# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdnwC0QAgVp-H6mhjjE9ba0I_vM0UxtY

Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a

scatter plot for age and fare columns in the titanic dataset.
"""

import plotly.graph_objs as go

import seaborn as sns

titanic = sns.load_dataset('titanic')

titanic.head()

fig = go.Figure()
fig.add_trace(go.Scatter(x=titanic.age , y = titanic.fare ,  mode = 'markers'))
fig.show()

"""**Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express.**"""

import plotly.express as px

tips = px.data.tips()

tips.head()

fig = px.box(tips , x='total_bill' , y = 'tip')
fig.show()

fig = px.box(tips , x='total_bill' , y = 'sex')
fig.show()

fig = px.box(tips , x='total_bill' , y = 'smoker')
fig.show()

fig = px.box(tips , x='total_bill' , y = 'day')
fig.show()

fig = px.box(tips , x='total_bill' , y = 'time')
fig.show()

fig = px.box(tips , x='total_bill' , y = 'size')
fig.show()

"""**Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.**
"""

tips.head()

fig = px.histogram(tips , x = tips.sex , y = tips.total_bill ,pattern_shape =  'smoker' , facet_col = 'day' )
fig.show()

"""**Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.**
"""

iris = px.data.iris()

iris.head()

"""**Q5. What is Distplot? Using Plotly express, plot a distplot.**

**A Distplot or distribution plot, depicts the variation in the data distribution.**
"""

